version: '3'
services:
  jupyter:
    image: koppektop/fastai
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - JUPYTER_PASSWORD=your_main_password
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - ./fastai:/fastai
      - ./data:/fastai/user_data
    command: ['/usr/bin/start', $USER]
    restart: unless-stopped
    logging:
      options:
        max-size: "50m"
